name: 'Scan and Upload'
description: 'Performs scan with SARIF upload to GitHub Security'
author: 'Midnight'
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  scan_actions:
    description: "Scan GitHub Actions code"
    required: false
    default: "true"
  scan_typescript:
    description: "Scan JavaScript/TypeScript code"
    required: false
    default: "true"
  scan_rust:
    description: "Scan Rust code"
    required: false
    default: "true"
  github_token:
    description: "GitHub token for API calls (optional)"
    required: false
    default: ""
  codeql_paths:
    description: "Comma-separated list of directories to scan with CodeQL"
    required: false
    default: "."  # defaults to repo root
  file-filter:
    description: 'File exclusion patterns (comma-separated glob patterns, e.g. !*.json,!test/*)'
    required: false
    default: ''

outputs:
  sarif-file:
    description: 'Path to generated SARIF files'
    value: 'scan_reports'

runs:
  using: 'composite'
  # recommended permissions to use:
  #
  # permissions:
  #   actions: read
  #   contents: read
  #   security-events: write
  #   statuses: write
  steps:
    - name: Set languages
      id: set-languages
      shell: bash
      run: |
        LANGS=()
        [ "${{ inputs.scan_actions }}" = "true" ] && LANGS+=("actions")
        [ "${{ inputs.scan_typescript }}" = "true" ] && LANGS+=("javascript-typescript")
        [ "${{ inputs.scan_rust }}" = "true" ] && LANGS+=("rust")
        echo "languages=${LANGS[*]}" >> $GITHUB_OUTPUT
        mkdir -p results

    - name: Run KICS Scan
      uses: checkmarx/kics-github-action@6b6fc1162a0f06704e4cca6e5f8e008ab20fabe5  #v2.1.16
      with:
        path: '.'
        output_path: 'results'
        output_formats: 'json,sarif'
        fail_on: high
        enable_comments: true
        exclude_paths: '.git,node_modules,dist,build'


    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8
      with:
        version: 'v0.67.2'
        scan-type: 'fs'
        scanners: 'vuln,secret,misconfig'
        format: 'sarif'
        output: 'results/trivy-results.sarif'
        #   severity: 'CRITICAL,HIGH,MEDIUM'
        trivy-config: trivy.yml

    - name: Run Scorecard Analysis
      uses: ossf/scorecard-action@99c09fe975337306107572b4fdf4db224cf8e2f2  #v2.4.3
      with:
        results_file: results/scorecard-results.sarif
        results_format: sarif
        publish_results: false
        repo_token: ${{ inputs.github_token }}

    - name: Upload trivy SARIF file
      uses: github/codeql-action/upload-sarif@ce729e4d353d580e6cacd6a8cf2921b72e5e310a
      if: success() || failure()
      continue-on-error: true
      with:
        sarif_file: results


    - name: Initialize CodeQL
      uses: github/codeql-action/init@ce729e4d353d580e6cacd6a8cf2921b72e5e310a
      with:
        source-root: ${{ inputs.codeql_paths }}
        languages: ${{ steps.set-languages.outputs.languages }}
        queries: security-and-quality

    - name: Analyze
      uses: github/codeql-action/analyze@ce729e4d353d580e6cacd6a8cf2921b72e5e310a
      with:
        upload: true
