name: 'Scan and Upload'
description: 'Performs scan with SARIF upload to GitHub Security'
author: 'Midnight'
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  scan_actions:
    description: "Scan GitHub Actions code"
    required: false
    default: "true"
  scan_typescript:
    description: "Scan JavaScript/TypeScript code"
    required: false
    default: "true"
  scan_rust:
    description: "Scan Rust code"
    required: false
    default: "true"
  github_token:
    description: "GitHub token for API calls (optional)"
    required: false
    default: ""
  fail_severity:
    description: "Fail the action when scans report this severity or higher (e.g. critical, high, medium). This must be set on private repos."
    required: false
    default: "critical"
  # file-filter:
  #   description: 'File exclusion patterns (comma-separated glob patterns, e.g. !*.json,!test/*)'
  #   required: false
  #   default: ''

runs:
  using: 'composite'
  # recommended permissions to use:
  #
  # permissions:
  #   actions: read
  #   contents: read
  #   security-events: write
  #   statuses: write
  steps:
    - name: Run OpenGrep
      shell: bash
      run: |
        mkdir -p scan_reports
        # TODO: setup renovate to bump this hash
        curl -fsSL https://raw.githubusercontent.com/opengrep/opengrep/6753c7e1e3bcd0c35fbd88894af03213b4640df4/install.sh | bash
        export PATH="$HOME/.opengrep/cli/latest:$PATH" && opengrep scan --config auto --taint-intrafile --dataflow-traces --force-color --sarif-output=scan_reports/opengrep.sarif

    - name: Run KICS Scan
      uses: checkmarx/kics-github-action@6b6fc1162a0f06704e4cca6e5f8e008ab20fabe5  #v2.1.16
      with:
        path: '.'
        output_path: 'scan_reports'
        output_formats: 'json,sarif'
        fail_on: high
        enable_comments: true
        exclude_paths: '.git,node_modules,dist,build'

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8
      with:
        version: 'v0.67.2'
        scan-type: 'fs'
        scanners: 'vuln,secret,misconfig'
        format: 'sarif'
        output: 'scan_reports/trivy-results.sarif'
        #   severity: 'CRITICAL,HIGH,MEDIUM'
        trivy-config: trivy.yml

    - name: Run Scorecard Analysis
      uses: ossf/scorecard-action@99c09fe975337306107572b4fdf4db224cf8e2f2  #v2.4.3
      with:
        results_file: scan_reports/scorecard-results.sarif.unprocessed
        results_format: sarif
        publish_results: false
        repo_token: ${{ inputs.github_token }}
        ref: ${{ github.sha }}

    - name: Fix SARIF for GitHub upload
      shell: bash
      run: |
        set -euo pipefail
        IFS=$'\n\t'

        # GitHub fails if artifactLocation.uri is empty
        # Replace empty URIs with a placeholder file
        if [ -f "./scan_reports/scorecard-results.sarif.unprocessed" ]; then
          jq '(.. | select(.uri? == "no file associated with this alert" or .uri? == "")) .uri = "README.md"' ./scan_reports/scorecard-results.sarif.unprocessed | \
          jq '.runs[].results[] |= (if .message.text == null or .message.text == "" then .message.text = ("Security issue detected by " + .ruleId) else . end)' \
          > ./scan_reports/scorecard-results.sarif
          echo "Fixed empty artifactLocation URIs in SARIF file"
        else
          echo "::warning:: No SARIF file generated from scorecard scan"
        fi

    - name: Upload SARIF files
      uses: github/codeql-action/upload-sarif@ce729e4d353d580e6cacd6a8cf2921b72e5e310a
      if: (success() || failure()) && github.event.repository.private == false
      continue-on-error: true
      with:
        sarif_file: scan_reports

    # Upload SARIF artifacts for private repositories
    - name: Upload Trivy SARIF artifacts
      if: (success() || failure()) && github.event.repository.private == true
      uses: actions/upload-artifact@v4
      with:
        name: sarif_reports
        path: scan_reports

    - name: Fail on severity
      shell: bash
      if: inputs.fail_severity != ''
      run: ./scripts/fail-on-severity.sh "${{ inputs.fail_severity }}"
