name: 'Scan and Upload'
description: 'Performs scan with SARIF upload to GitHub Security'
author: 'Midnight'
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  file-filter:
    description: 'File exclusion patterns (comma-separated glob patterns, e.g. !*.json,!test/*)'
    required: false
    default: ''

outputs:
  sarif-file:
    description: 'Path to generated SARIF files'
    value: 'scan_reports'

runs:
  using: 'composite'
  # recommended permissions to use:
  #
  # permissions:
  #   actions: read
  #   contents: read
  #   security-events: write
  #   statuses: write
  steps:
    - name: Run KICS Scan
      uses: checkmarx/kics-github-action@6b6fc1162a0f06704e4cca6e5f8e008ab20fabe5  #v2.1.16
      with:
        path: '.'
        output_path: 'results'
        output_formats: 'json,sarif'
        fail_on: high
        enable_comments: true
        exclude_paths: '.git,node_modules,dist,build'

    - name: Upload kics SARIF file to GitHub Security
      uses: github/codeql-action/upload-sarif@ce729e4d353d580e6cacd6a8cf2921b72e5e310a  #CodeQL Bundle v2.23.6
      if: success() || failure()
      continue-on-error: true
      with:
        sarif_file: results/results.sarif

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8
      with:
        version: 'v0.67.2'
        scan-type: 'fs'
        scanners: 'vuln,secret,misconfig'
        format: 'sarif'
        output: 'results/trivy-results.sarif'
        #   severity: 'CRITICAL,HIGH,MEDIUM'
        trivy-config: trivy.yml

    - name: Upload trivy SARIF file
      uses: github/codeql-action/upload-sarif@ce729e4d353d580e6cacd6a8cf2921b72e5e310a
      if: success() || failure()
      continue-on-error: true
      with:
        sarif_file: results/trivy-results.sarif
        category: 'trivy-fs'

    - name: Run Scorecard Analysis
      uses: ossf/scorecard-action@99c09fe975337306107572b4fdf4db224cf8e2f2  #v2.4.3
      with:
        results_file: results/scorecard-results.sarif
        results_format: sarif
        publish_results: false
        repo_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload scorecard SARIF results to code-scanning
      uses: github/codeql-action/upload-sarif@ce729e4d353d580e6cacd6a8cf2921b72e5e310a  #CodeQL Bundle v2.23.6
      if: success() || failure()
      with:
        sarif_file: results/scorecard-results.sarif
        category: 'scorecard'

    - name: Initialize CodeQL
      uses: github/codeql-action/init@ce729e4d353d580e6cacd6a8cf2921b72e5e310a
      with:
        languages: actions,javascript-typescript,rust
        queries: security-and-quality

    - name: Analyze
      uses: github/codeql-action/analyze@ce729e4d353d580e6cacd6a8cf2921b72e5e310a
      with:
        upload: true
