name: 'Scan and Upload'
description: 'Performs scan with SARIF upload to GitHub Security'
author: 'Midnight'
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  scan_actions:
    description: "Scan GitHub Actions code"
    required: false
    default: "true"
  scan_typescript:
    description: "Scan JavaScript/TypeScript code"
    required: false
    default: "true"
  scan_rust:
    description: "Scan Rust code"
    required: false
    default: "true"
  github_token:
    description: "GitHub token for API calls (optional)"
    required: false
    default: ""
  fail_severity:
    description: "Fail the action when scans report this severity or higher (e.g. critical, high, medium). This must be set on private repos."
    required: false
    default: "critical"
  # file-filter:
  #   description: 'File exclusion patterns (comma-separated glob patterns, e.g. !*.json,!test/*)'
  #   required: false
  #   default: ''

runs:
  using: 'composite'
  # recommended permissions to use:
  #
  # permissions:
  #   actions: read
  #   contents: read
  #   pull-requests: write
  #   security-events: write
  #   statuses: write
  steps:
    - name: Install cosign (used by OpenGrep)
      uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad  #v4.0.0

    - name: Run OpenGrep
      shell: bash
      run: |
        mkdir -p scan_reports
        # renovate: datasource=github-releases packageName=opengrep/opengrep
        opengrep_version="71c379ba378f00c36a140b8b11253599d699694e"
        curl -fsSL https://raw.githubusercontent.com/opengrep/opengrep/${opengrep_version}/install.sh | bash
        export PATH="$HOME/.opengrep/cli/latest:$PATH" && opengrep scan --config auto --taint-intrafile --dataflow-traces --force-color --sarif-output=scan_reports/opengrep.sarif

    - name: Run KICS Scan
      uses: checkmarx/kics-github-action@6b6fc1162a0f06704e4cca6e5f8e008ab20fabe5  #v2.1.16
      with:
        path: '.'
        output_path: 'scan_reports'
        output_formats: 'json,sarif'
        fail_on: high
        enable_comments: true
        exclude_paths: '.git,node_modules,dist,build'

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8
      with:
        version: 'v0.67.2'
        scan-type: 'fs'
        scanners: 'vuln,secret,misconfig'
        format: 'sarif'
        output: 'scan_reports/trivy-results.sarif'
        #   severity: 'CRITICAL,HIGH,MEDIUM'
        trivy-config: trivy.yml

    - name: Run Scorecard cli
      shell: bash
      env:
         GITHUB_AUTH_TOKEN: ${{ inputs.github_token }}
      run: |
        wget https://github.com/ossf/scorecard/releases/download/v5.4.0/scorecard_5.4.0_linux_amd64.tar.gz
        tar -xf ./scorecard_5.4.0_linux_amd64.tar.gz scorecard
        ./scorecard --local . --format json --output scan_reports/scorecard-results.json --checks "Signed-Releases,Vulnerabilities,Binary-Artifacts,Branch-Protection,Dangerous-Workflow,Security-Policy,License,Pinned-Dependencies,Code-Review,Contributors,Dependency-Update-Tool,CI-Tests,Packaging,Token-Permissions"

        echo "Converting Scorecard JSON to SARIF format"
        cat ./scan_reports/scorecard-results.json | jq -f ./scan/scripts/scorecard.jq > scan_reports/scorecard-results.sarif

    - name: Upload SARIF files
      uses: github/codeql-action/upload-sarif@ce729e4d353d580e6cacd6a8cf2921b72e5e310a
      if: (success() || failure()) && github.event.repository.private == false
      continue-on-error: true
      with:
        sarif_file: scan_reports

    # Upload SARIF artifacts for private repositories
    - name: Upload Trivy SARIF artifacts
      if: (success() || failure()) && github.event.repository.private == true
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f  #v6.0.0
      with:
        name: sarif_reports
        path: scan_reports

    - name: Fail on severity
      shell: bash
      if: inputs.fail_severity != ''
      env:
        INPUT_SEVERITY: ${{ inputs.fail_severity }}
      run: ./scan/scripts/fail-on-severity.sh "$INPUT_SEVERITY"
