# Example workflow for using cargo-audit with Checkmarx SARIF upload
# This workflow demonstrates how to scan Rust dependencies and upload results to Checkmarx

name: Rust Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  cargo-audit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  #v5.0.0
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9
      
      - name: Install cargo-audit
        run: cargo install cargo-audit
      
      - name: Run cargo audit and generate SARIF
        run: |
          # Generate SARIF report
          # Using || true to ensure workflow continues even if vulnerabilities are found
          cargo audit --format sarif > cargo-audit.sarif || true
          
          # Display summary for logs
          echo "Cargo audit completed. SARIF file size: $(stat -c%s cargo-audit.sarif) bytes"
      
      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@16df4fbc19aea13d921737861d6c622bf3cefe23  #v3
        with:
          sarif_file: cargo-audit.sarif
          category: cargo-audit
      
      - name: Upload SARIF to Checkmarx
        uses: midnight-ntwrk/upload-sarif-github-action@46581f193c493f6bf464cca059dd7f4238307373  #v1
        with:
          sarif-file: cargo-audit.sarif
          project-name: ${{ github.event.repository.name }}
          cx-client-id: ${{ secrets.CX_CLIENT_ID }}
          cx-client-secret: ${{ secrets.CX_CLIENT_SECRET_EU }}
          cx-tenant: ${{ secrets.CX_TENANT }}
      
      - name: Upload SARIF as artifact (optional)
        uses: actions/upload-artifact@de65e23aa2b7e23d713bb51fbfcb6d502f8667d8  #v4
        with:
          name: cargo-audit-sarif
          path: cargo-audit.sarif
          retention-days: 30
