# Example workflow combining multiple security tools with Checkmarx SARIF upload
# This demonstrates how to aggregate results from different scanners

name: Comprehensive Security Scan

on:
  push:
    branches: [ main, release/** ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  rust-audit:
    runs-on: ubuntu-latest
    name: Rust Dependencies Audit
    
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  #v5.0.0
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9
      
      - name: Run cargo-audit
        run: |
          cargo install cargo-audit
          cargo audit --format sarif > rust-audit.sarif || true
      
      - name: Upload Rust audit to Checkmarx
        uses: midnightntwrk/upload-sarif-github-action@46581f193c493f6bf464cca059dd7f4238307373  #v1
        with:
          sarif-file: rust-audit.sarif
          project-name: ${{ github.event.repository.name }}-rust
          cx-client-id: ${{ secrets.CX_CLIENT_ID }}
          cx-client-secret: ${{ secrets.CX_CLIENT_SECRET_EU }}
          cx-tenant: ${{ secrets.CX_TENANT }}
      
      - name: Save SARIF artifact
        uses: actions/upload-artifact@de65e23aa2b7e23d713bb51fbfcb6d502f8667d8  #v4

        with:
          name: rust-audit-sarif
          path: rust-audit.sarif

  container-scan:
    runs-on: ubuntu-latest
    name: Container Security Scan
    if: hashFiles('**/Dockerfile') != ''
    
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  #v5.0.0
      
      - name: Run Trivy container scan
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy.sarif'
      
      - name: Upload Trivy results to Checkmarx
        uses: midnightntwrk/upload-sarif-github-action@46581f193c493f6bf464cca059dd7f4238307373  #v1
        with:
          sarif-file: trivy.sarif
          project-name: ${{ github.event.repository.name }}-container
          cx-client-id: ${{ secrets.CX_CLIENT_ID }}
          cx-client-secret: ${{ secrets.CX_CLIENT_SECRET_EU }}
          cx-tenant: ${{ secrets.CX_TENANT }}
      
      - name: Save SARIF artifact
        uses: actions/upload-artifact@de65e23aa2b7e23d713bb51fbfcb6d502f8667d8  #v4
        with:
          name: trivy-sarif
          path: trivy.sarif

  semgrep-scan:
    runs-on: ubuntu-latest
    name: Semgrep SAST
    
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  #v5.0.0
      
      - name: Run Semgrep
        id: semgrep
        # TODO: this action is deprecated.
        uses: returntocorp/semgrep-action@713efdd345f3035192eaa63f56867b88e63e4e5d
        with:
          generateSarif: true
      
      - name: Upload Semgrep results to Checkmarx
        if: always() && steps.semgrep.outputs.sarif != ''
        uses: midnightntwrk/upload-sarif-github-action@46581f193c493f6bf464cca059dd7f4238307373  #v1
        with:
          sarif-file: semgrep.sarif
          project-name: ${{ github.event.repository.name }}-sast
          cx-client-id: ${{ secrets.CX_CLIENT_ID }}
          cx-client-secret: ${{ secrets.CX_CLIENT_SECRET_EU }}
          cx-tenant: ${{ secrets.CX_TENANT }}

  upload-all-to-github:
    runs-on: ubuntu-latest
    name: Upload all results to GitHub Security
    needs: [rust-audit, container-scan, semgrep-scan]
    if: always()
    
    steps:
      - name: Download all SARIF artifacts
        uses: actions/download-artifact@abefc31eafcfbdf6c5336127c1346fdae79ff41c  #v4
        with:
          pattern: '*-sarif'
      
      - name: Upload Rust audit SARIF to GitHub
        if: hashFiles('rust-audit-sarif/rust-audit.sarif') != ''
        uses: github/codeql-action/upload-sarif@02ab253bd299d261d00cdf8a9bca38fea2697d50  # v3.29.2
        with:
          sarif_file: rust-audit-sarif/rust-audit.sarif
          category: rust-audit
      
      - name: Upload Trivy SARIF to GitHub
        if: hashFiles('trivy-sarif/trivy.sarif') != ''
        uses: github/codeql-action/upload-sarif@02ab253bd299d261d00cdf8a9bca38fea2697d50  # v3.29.2
        with:
          sarif_file: trivy-sarif/trivy.sarif
          category: container-scan
