name: 'Checkmarx Full Scan and Upload'
description: 'Performs complete Checkmarx scan with SARIF upload to both GitHub Security and Checkmarx BYOR'
author: 'Midnight'
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  project-name:
    description: 'Checkmarx project name'
    required: true
    default: ${{ github.event.repository.name }}
  cx-client-id:
    description: 'Checkmarx OAuth2 client ID'
    required: true
  cx-client-secret:
    description: 'Checkmarx OAuth2 client secret'
    required: true
  cx-tenant:
    description: 'Checkmarx tenant'
    required: true
  base-uri:
    description: 'Checkmarx server URL'
    required: false
    default: 'https://eu-2.ast.checkmarx.net/'
  scs-repo-token:
    description: 'GitHub token for SCS scanning (Supply Chain Security)'
    required: true
  additional-params:
    description: 'Additional parameters for Checkmarx scan'
    required: false
    default: ''
  upload-to-github:
    description: 'Upload SARIF to GitHub Security (automatically disabled for private repos)'
    required: false
    default: 'true'
  upload-to-checkmarx:
    description: 'Upload SARIF to Checkmarx via BYOR'
    required: false
    default: 'true'

outputs:
  scan-id:
    description: 'Checkmarx scan ID'
    value: ${{ steps.checkmarx-scan.outputs.scan-id }}
  sarif-file:
    description: 'Path to generated SARIF file'
    value: 'cx_result.sarif'

runs:
  using: 'composite'
  steps:
    - name: Check Checkmarx EU2 status
      shell: bash
      run: |
        # URL of the EU2 status page
        url="https://eu2-status.ast.checkmarx.net/"
        html=$(curl -s "$url")

        if echo "$html" | grep -q "Operating Normally"; then
          echo "✅ Checkmarx EU2 status: Operating Normally"
        else
          echo "⚠️ Checkmarx EU2 may be experiencing issues"
          echo "Status page: $url"
          echo "Proceeding without breaking the build"
          # No exit - let the action continue to the actual scan
        fi

    - name: Check Checkmarx IND server health
      shell: bash
      run: |
        response=$(curl -s -o /dev/null -w "%{http_code}" https://ind-status.ast.checkmarx.net/)
        if [ "$response" = "200" ]; then
          echo "✅ Checkmarx IND server: Healthy (HTTP 200)"
        else
          echo "⚠️ Checkmarx IND server returned: HTTP $response"
          echo "Proceeding without breaking the build"
          # No exit - let the action continue to the actual scan
        fi

    - name: Run Checkmarx scan
      id: checkmarx-scan
      uses: checkmarx/ast-github-action@fa338ce82069b297c4852ac77e2d168db9fb56d8 #2.3.21
      with:
        cx_tenant: ${{ inputs.cx-tenant }}
        base_uri: ${{ inputs.base-uri }}
        cx_client_id: ${{ inputs.cx-client-id }}
        cx_client_secret: ${{ inputs.cx-client-secret }}
        additional_params: >
          --scs-repo-url https://github.com/${{ github.repository }}
          --scs-repo-token ${{ inputs.scs-repo-token }}
          --report-format sarif
          ${{ inputs.additional-params }}

    - name: Fix SARIF for GitHub upload
      shell: bash
      run: |
        # GitHub fails if artifactLocation.uri is empty
        # Replace empty URIs with a placeholder file
        if [ -f "./cx_result.sarif" ]; then
          mv ./cx_result.sarif ./cx_result.sarif.orig
          jq '.runs |= map(.results |= map(.locations |= map(if .physicalLocation.artifactLocation.uri == "" then .physicalLocation.artifactLocation.uri = "file:/README.md" else . end)))' cx_result.sarif.orig > cx_result.sarif
          echo "Fixed empty artifactLocation URIs in SARIF file"
          
          # Fix missing message text that causes newer codeql-action versions to fail
          mv ./cx_result.sarif ./cx_result.sarif.tmp
          jq '.runs[].results[] |= (if .message.text == null or .message.text == "" then .message.text = ("Security issue detected by " + .ruleId) else . end)' cx_result.sarif.tmp > cx_result.sarif
          rm -f cx_result.sarif.tmp cx_result.sarif.orig
          echo "Fixed missing message text in SARIF file"
        else
          echo "::warning::No SARIF file generated from Checkmarx scan"
        fi

    - name: Upload SARIF to GitHub Security
      if: ${{ inputs.upload-to-github == 'true' && github.event.repository.private == false }}
      uses: github/codeql-action/upload-sarif@9fde80919ae2e536afc500421fa2c837105e21a1  # v3.29.2
      with:
        sarif_file: cx_result.sarif
      continue-on-error: true

    - name: Upload SARIF to Checkmarx BYOR
      if: ${{ inputs.upload-to-checkmarx == 'true' && hashFiles('cx_result.sarif') != '' }}
      # Note: When repo is private, this requires checking out the action first
      # Once public, can use: midnightntwrk/upload-sarif-github-action@main
      uses: ./upload-sarif-github-action
      with:
        sarif-file: cx_result.sarif
        project-name: ${{ inputs.project-name }}
        cx-client-id: ${{ inputs.cx-client-id }}
        cx-client-secret: ${{ inputs.cx-client-secret }}
        cx-tenant: ${{ inputs.cx-tenant }}
        base-uri: ${{ inputs.base-uri }}
      continue-on-error: true
