# Workflow for local testing with act
# Usage: act -W .github/workflows/local-test.yaml -s CX_CLIENT_ID=xxx -s CX_CLIENT_SECRET_EU=xxx -s CX_TENANT=xxx

name: Local Test

on:
  workflow_dispatch:
  push:
    branches: [ test-local ]

jobs:
  test-action:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Create test SARIF
        run: |
          cat > test.sarif << 'EOF'
          {
            "version": "2.1.0",
            "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
            "runs": [
              {
                "tool": {
                  "driver": {
                    "name": "act-test",
                    "version": "1.0.0"
                  }
                },
                "results": [
                  {
                    "ruleId": "ACT001",
                    "message": {
                      "text": "Test from act local runner"
                    },
                    "locations": [
                      {
                        "physicalLocation": {
                          "artifactLocation": {
                            "uri": "test.rs"
                          },
                          "region": {
                            "startLine": 1
                          }
                        }
                      }
                    ]
                  }
                ]
              }
            ]
          }
          EOF
      
      - name: Test upload action
        uses: ./
        with:
          sarif-file: test.sarif
          project-name: act-local-test-${{ github.run_id }}
          cx-client-id: ${{ secrets.CX_CLIENT_ID }}
          cx-client-secret: ${{ secrets.CX_CLIENT_SECRET_EU }}
          cx-tenant: ${{ secrets.CX_TENANT }}